goals:
  - positions:
    - position: { x: -8.0, y: -4.0, z: 0.0 }
    - position: { x: -8.0, y: 4.0, z: 0.0 }
    - position: { x: 8.0, y: 4.0, z: 0.0 }
    - position: { x: 8.0, y: -4.0, z: 0.0 }
  -positions:
    - position: { x: -4.0, y: -4.0, z: 0.0 }
    - position: { x: -4.0, y: 4.0, z: 0.0 }
    - position: { x: 4.0, y: 4.0, z: 0.0 }
    - position: { x: 4.0, y: -4.0, z: 0.0 }