goals:
  - position: { x: 8.0, y: 0.0, z: 0.0 }
  - position: { x: 8.0, y: 0.0, z: 0.0 }
  - position: { x: 8.0, y: 0.0, z: 0.0 }
  - position: { x: 8.0, y: 4.0, z: 0.0 }
  - position: { x: 8.0, y: 4.0, z: 0.0 }
  - position: { x: 8.0, y: 4.0, z: 0.0 }
  - position: { x: 8.0, y: -4.0, z: 0.0 }
  - position: { x: 8.0, y: -4.0, z: 0.0 }
  - position: { x: 8.0, y: -4.0, z: 0.0 }
