GoToPosition:
  frame: "World"
  x: 1.0
  y: 0.0
  z: 0.0

GoToPose:
  frame: "World"
  x: 3.5
  y: 3.9
  z: 0.0
  qx: 2.0
  qy: 1.0
  qz: 1.0
  qw: 1.0

TrackVelocities:
  frame: "World"
  shape: "circle"
  closed: true
  linear_x: 0.5
  linear_y: 0.5
  linear_z: 0.5
  angular_x: 0.5
  angular_y: 0.5
  angular_z: 0.5
  circle:
    radius: 1.0
    num_points: 3600
  square:
    hight: 2
    num_points: 3600
  spiral:
    start_radius: 0.5
    end_radius: 2.0
    num_loops: 5
    num_points: 7200