goals:
  - positions:
    - position:
      x: -2.0
      y: -1.0
      z: 0.0
    - position:
      x: -2.0
      y: 1.0
      z: 0.0
    - position:
      x: 2.0
      y: 1.0
      z: 0.0
    - position:
      x: 2.0
      y: -1.0
      z: 0.0
  -positions:
    - position:
      x: -1.0
      y: -1.0
      z: 0.0
    - position:
      x: -1.0
      y: -1.0
      z: 0.0
    - position:
      x: -1.0
      y: 1.0
      z: 0.0
    - position:
      x: -1.0
      y: 1.0
      z: 0.0
    - position:
      x: -1.0
      y: 1.0
      z: 0.0
frame: "global"